### ISSUE TITLE
New icon request: Guake

### ISSUE THREAD

**Issue by ghost** [captiva-project/captiva-icon-theme#10]

**Comment by fsvh** [comment]
Hello @elvisd thanks for request icons :). Just if in the future you can add your icons requests [in this link](http://captiva-project.github.io/icon-requests/) and checkout how to really add a request on [this video](https://www.youtube.com/watch?v=qEzqEndVqto&list=UUKqoYJU4D6BrMFLWk_Nhgjg&index=1) like this I can have all request in one place only. :100: Thanks

**Comment by fsvh** [comment]
already added guake terminal
